### ISSUE TITLE
Erro when calling :Defx

### ISSUE THREAD

**Issue by dimascyriaco** [Shougo/defx.nvim#10]
# Problems summary

I'm getting an error when trying to open the Defx buffer.

```
[defx] Vim(call):E117: Unknown function: _defx_init                                                                                               
[defx] function defx#util#call_defx[2]..defx#start[1]..defx#initialize[1]..defx#init#_initialize[1]..defx#init#_channel, line 11                  
[defx] defx failed to load. Try the :UpdateRemotePlugins command and restart Neovim. See also :CheckHealth.                                       
Error detected while processing function defx#util#call_defx[2]..defx#start:                                                                      
line    8:                                                                                                                                        
E117: Unknown function: _defx_start                                                                                                               
E15: Invalid expression: _defx_start(paths, context)         
```

Executing `:UpdateRemotePlugins` returns this:

```
Encountered SyntaxError loading plugin at /home/dimas/.cache/dein/.cache/init.vim/.dein/rplugin/python3/defx: invalid syntax (view.py, line 21)   
Traceback (most recent call last):                                                                                                                
  File "/usr/local/lib/python3.5/dist-packages/neovim/plugin/host.py", line 130, in _load                                                         
    module = imp.load_module(name, file, pathname, descr)                                                                                         
  File "/usr/lib/python3.5/imp.py", line 244, in load_module                                                                                      
    return load_package(name, filename)                                                                                                           
  File "/usr/lib/python3.5/imp.py", line 216, in load_package                                                                                     
    return _load(spec)                                                                                                                            
  File "<frozen importlib._bootstrap>", line 693, in _load                                                                                        
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked                                                                               
  File "/home/dimas/.cache/dein/.cache/init.vim/.dein/rplugin/python3/defx/view.py", line 21                                                      
    self._vim: Nvim = vim                                                                                                                         
             ^                                                                                                                                    
SyntaxError: invalid syntax                                                                                                                       
remote/host: python3 host registered plugins ['denite', 'deoplete']                                                                               
remote/host: generated rplugin manifest: /home/dimas/.local/share/nvim/rplugin.vim
```

## Expected

Expected the buffer to open.

## Environment Information

 * defx version(SHA1): 52b8b1881f0f7be84ca7ab8dbd80e7a8a6378e8b

 * OS: Ubuntu 18.04

 * neovim/Vim version: v0.3.2-69-ga225374

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
  1 health#deoplete#check                                                           
  2 ========================================================================        
  3 ## deoplete.nvim                                                                
  4   - OK: has("nvim") was successful                                              
  5   - OK: exists("v:t_list") was successful                                       
  6   - OK: has("timers") was successful                                            
  7   - OK: has("python3") was successful                                           
  8   - INFO: If you're still having problems, try the following commands:          
  9     $ export NVIM_PYTHON_LOG_FILE=/tmp/log                                      
 10     $ export NVIM_PYTHON_LOG_LEVEL=DEBUG                                        
 11     $ nvim                                                                      
 12     $ cat /tmp/log_{PID}                                                        
 13     and then create an issue on github                                          
 14                                                                                 
 15 health#nvim#check                                                               
 16 ========================================================================        
 17 ## Configuration                                                                
 18   - OK: no issues found                                                         
 19                                                                                 
 20 ## Performance                                                                  
 21   - OK: Build type: RelWithDebInfo                                              
 22                                                                                 
 23 ## Remote Plugins                                                               
 24   - WARNING: ".dein" is not registered.                                         
 25   - WARNING: Out of date                                                        
 26     - ADVICE:                                                                   
 27       - Run `:UpdateRemotePlugins`                                              
 28                                                                                 
 29 ## terminal                                                                     
 30   - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177                
 31   - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~                           
 32   - INFO: $VTE_VERSION='4205'
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
if &compatible
  set nocompatible
endif

set runtimepath+=/home/dimas/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('/home/dimas/.cache/dein')
  call dein#begin('/home/dimas/.cache/dein')

  call dein#add('/home/dimas/.cache/dein/repos/github.com/Shougo/dein.vim')

  call dein#add('Shougo/denite.nvim')
  call dein#add('Shougo/deoplete.nvim')
	call dein#add('Shougo/defx.nvim')

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable

if dein#check_install()
  call dein#install()
endif

let mapleader = " "
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. start neovim
 2. execute :Defx

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment]
Please see defx requirements.

```
Note: defx requires Neovim(latest is recommended) or Vim8 with Python3.6.1+ and timers(neovim ver.0.2.0+) enabled. See requirements if you aren't sure whether you have this.
```

You need to install Python 3.6.1 or above.

**Comment by Shougo** [comment]
Your Python is version 3.5 from the log.

**Comment by dimascyriaco** [comment]
Thank you.

**Comment by FSCYT** [comment]
> Your Python is version 3.5 from the log.

I have this same issue with Python 3.9.9 and Nvim 0.6.0. I used :UpdateRemotePlugins

**Comment by Shougo** [comment]
Really??? Really???

You should check what version of Python is used in `neovim`.

```
python3 import sys
python3 print(sys.version_info)
```

**Comment by FSCYT** [comment]
> Really??? Really???
> 
> You should check what version of Python is used in `neovim`.
> 
> ```
> python3 import sys
> python3 print(sys.version_info)
> ```

It randomly got fixed, I'm guessing it could be pynvim. But I don't know

**Comment by Shougo** [comment]
Wow...  You should not install old Python.
