### ISSUE TITLE
new_file action failed when directory name contains '#'

### ISSUE THREAD

**Issue by mars90226** [Shougo/defx.nvim#104]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
new_file action failed when directory name contains '#'.

## Expected
Can create new file.

## Environment Information

 * defx version(SHA1): 1936b08fba25d24575e5f80fa651ab10daeb9c3d

 * OS: Ubuntu 18.04 Linux 4.18.20-041820-generic x86_64 GNU/Linux

 * neovim/Vim version: NVIM v0.4.0-335-g2816bc862

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: screen-256color
  - INFO: default-terminal: xterm-256color
  - ERROR: $TERM differs from the tmux `default-terminal` setting. Colors might look wrong.
    - ADVICE:
      - $TERM may have been set by some rc (.bashrc, .zshrc, ...).

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python version: 2.7.15
  - INFO: pynvim version: 0.1.13 (outdated; from /usr/local/lib/python2.7/dist-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.3.2

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.6.7
  - INFO: pynvim version: 0.2.6 (outdated; from /usr/local/lib/python3.6/dist-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.3.2

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v10.6.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```
## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/.vim/plugged/defx.nvim/

autocmd FileType defx call s:defx_settings()

function! s:defx_settings()
	nnoremap <silent><buffer><expr> N
				\ defx#do_action('new_file')
endfunction
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. mkdir '#test'
 2. cd '#test'
 3. nvim -u minimal.vimrc
 4. :Defx
 5. press 'N'

## Generate a logfile if appropriate
This is the output of `:message`.
```
Error detected while processing function defx#call_action[7]..defx#util#rpcrequest:
line   18:
error caught in request handler '_defx_do_action [['new_file', [], {'columns': 'mark:filename:type', 'auto_cd': False, 'show_ignored_files': False, 'root_marker': '[in]: ', 'resume': False,
'sort': 'filename', 'listed': False, 'new': False, 'direction': '', 'visual_end': 0, 'winheight': 30, 'profile': False, 'search': '', 'buffer_name': 'default', 'winwidth': 90, 'prev_bufnr':
2, 'split': 'no', 'visual_start': 0, 'cursor': 1, 'prev_winid': 1000, 'wincol': 47, 'winrow': 18, 'toggle': False}]]':
Traceback (most recent call last):
  File "/root/.vim/plugged/defx.nvim/rplugin/python3/defx/__init__.py", line 41, in do_action
    self._rplugin.do_action(args)
  File "/root/.vim/plugged/defx.nvim/rplugin/python3/defx/rplugin.py", line 37, in do_action
    view.do_action(args[0], args[1], args[2])
  File "/root/.vim/plugged/defx.nvim/rplugin/python3/defx/view.py", line 98, in do_action
    ret = action.do_action(self, defx, action_name, context)
  File "/root/.vim/plugged/defx.nvim/rplugin/python3/defx/action.py", line 47, in do_action
    action.func(view, defx, context)
  File "/root/.vim/plugged/defx.nvim/rplugin/python3/defx/kind/file.py", line 238, in _new_file
    'Please input a new filename: ', '', 'file')
  File "/root/.vim/plugged/defx.nvim/rplugin/python3/defx/util.py", line 32, in cwd_input
    vim.command(f'silent lcd {cwd}')
  File "/usr/local/lib/python3.6/dist-packages/neovim/api/nvim.py", line 272, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/neovim/api/nvim.py", line 170, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/neovim/msgpack_rpc/session.py", line 100, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b"Vim(lcd):E194: No alternate file name to substitute for '#'"
Press ENTER or type command to continue
```

## Screen shot (if possible)
![defx_not_escape_path_in_new_file](https://user-images.githubusercontent.com/1523214/54351895-85298500-468b-11e9-9fd1-d6e277c65d33.png)

**Comment by mars90226** [comment]
Thanks!
