### ISSUE TITLE
Cannot set custom root

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#110]
With the following minimal vimrc:

```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim

filetype plugin indent on

function! Root(path) abort
    return fnamemodify(a:path, ':t') . '/'
endfunction
call defx#custom#source('file', {'root': 'Root'})
```
if I run `:Defx` I get:
```
error caught in async handler '_defx_async_action [['check_redraw', [], {'columns': 'mark:filename:type', 'auto_cd': False, 'prev_bufnr': 1, 'root_marker': '[in]: ', 'resume': False, 'auto_recursive_level': 0, 'so
rt': 'filename', 'listed': False, 'new': False, 'ignored_files': '.*', 'direction': '', 'visual_end': 0, 'winheight': 30, 'profile': False, 'search': '', 'buffer_name': 'default', 'winwidth': 90, 'split': 'no', 'v
isual_start': 0, 'cursor': 1, 'prev_winid': 1000, 'wincol': 53, 'winrow': 18, 'show_ignored_files': False, 'toggle': False}]]'
Traceback (most recent call last):
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/__init__.py", line 45, in async_action
    self._rplugin.do_action(args)
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/rplugin.py", line 37, in do_action
    view.do_action(args[0], args[1], args[2])
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/view.py", line 78, in do_action
    ret = action.do_action(self, defx, action_name, context)
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/action.py", line 47, in do_action
    action.func(view, defx, context)
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/kind/file.py", line 109, in _check_redraw
    root = defx.get_root_candidate()
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/defx.py", line 58, in get_root_candidate
    root = self._source.get_root_candidate(self._context, Path(self._cwd))
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/source/file.py", line 36, in get_root_candidate
    word = self.vim.call(self.vars['root'], path)
  File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 299, in call
    return self.request('nvim_call_function', name, args, **kwargs)
  File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 93, in request
    v = self._yielding_request(method, args)
  File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 162, in _yielding_request
    self._async_session.request(method, args, response_cb)
  File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/msgpack_rpc/async_session.py", line 45, in request
    self._msgpack_stream.send([0, request_id, method, args])
  File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/msgpack_rpc/msgpack_stream.py", line 34, in send
    self.loop.send(self._packer.pack(msg))
  File "msgpack/_packer.pyx", line 282, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 288, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 285, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 261, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 261, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 261, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 279, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'PosixPath' object
```

**Comment by petobens** [comment]
Thank you!
