### ISSUE TITLE
api error when creating new defx

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#111]
Consider the following (not so minimal) vimrc:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim
set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim

filetype plugin indent on


" Denite
if executable('fd')
    call denite#custom#var('directory_rec', 'command',
        \ ['fd', '--type', 'd', '--follow', '--hidden', '--exclude', '.git',
        \ ''])
endif
function! s:defx_open(context)
    let path = a:context['targets'][0]['action__path']
    let file = fnamemodify(path, ':p')
    let file_search = filereadable(expand(file)) ? ' -search=' . file : ''
    let dir = denite#util#path2directory(path)
    if &filetype ==# 'defx'
      call defx#call_action('cd', [dir])
      call defx#call_action('search', [file])
    else
        execute('Defx ' . dir . file_search)
    endif
endfunction
function! s:defx_preview(context)
    let path = a:context['targets'][0]['action__path']
    let file = fnamemodify(path, ':p')
    let file_search = filereadable(expand(file)) ? ' -search=' . file : ''
    let dir = denite#util#path2directory(path)
    let denite_winwidth = &columns
    execute 'silent rightbelow vertical pedit! defx_tmp'
    wincmd P
    silent! setlocal nobuflisted
    execute 'vert resize ' . (denite_winwidth / 3)
    execute 'Defx -new -split=no -auto-recursive-level=1 ' .  dir . file_search
    call defx#call_action('open_tree')
    wincmd p
endfunction
call denite#custom#action('buffer,directory,file,openable,dirmark', 'defx',
        \ function('s:defx_open'))
call denite#custom#action('directory,directory_rec,directory_rec/noignore',
        \ 'preview', function('s:defx_preview'), {'is_quit': 0})
call denite#custom#map('insert', '<A-v>', '<denite:do_action:preview>',
        \ 'noremap')


" Defx
augroup ps_defx
    au!
    au FileType defx call s:defx_settings()
augroup END

function! s:defx_settings()
    function! s:denite_dir_rec(context) abort
        let narrow_dir = a:context.targets[0]
        execute 'Denite -default-action=defx ' .
                    \ 'directory_rec:' . narrow_dir
    endfunction
    nnoremap <silent><buffer><expr> <A-c>
                \ defx#do_action('call', '<SID>denite_dir_rec')
endfunction
```
Now open `nvim` and run
1. `:Defx`
2. Once the `Defx` buffer opens press `<Alt-c>` on a directory candidate
3. Once the denite buffer opens press `<Alt-v>` on denite candidate
The last step gives the following error:

```
[denite] Traceback (most recent call last):
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/rplugin.py", line 25, in start
[denite]     return ui.start(args[0], context)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 79, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 157, in _start
[denite]     status = self._prompt.start()
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/prompt.py", line 201, in start
[denite]     raise e
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/prompt.py", line 191, in start
[denite]     interval=self.harvest_interval,
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/prompt.py", line 96, in on_keypress
[denite]     ret = self.action.call(self, m.group('action'))
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/prompt/action.py", line 139, in call
[denite]     return fn(prompt, params)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/action.py", line 18, in _do_action
[denite]     return prompt.denite.do_action(params)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 719, in do_action
[denite]     self._denite.do_action(self._context, action_name, candidates)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/denite.py", line 243, in do_action
[denite]     action['kind'], action['name'], context)
[denite]   File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 299, in call
[denite]     return self.request('nvim_call_function', name, args, **kwargs)
[denite]   File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
[denite]     raise self.error_wrapper(err)
[denite] pynvim.api.nvim.NvimError: b"Vim(return):error caught in request handler '_defx_start [[['/home/pedro/git-repos/private/dotfiles/vim/bundle/repos/'], {'columns': 'mark:filename:type', 'auto_cd': 0, 'prev_
bufnr': 3, 'root_marker': '[in]: ', 'resume': 0, 'auto_recursive_level': 1, 'sort': 'filename', 'listed': 0, 'new': 1, 'ignored_files': '.*', 'direction': '', 'visual_end': 0, 'winheight': 30, 'profile': 0, 'searc
h': '', 'buffer_name': 'default', 'winwidth': 90, 'split': 'no', 'visual_start': 0, 'cursor': 1, 'prev_winid': 1002, 'wincol': 53, 'winrow': 18, 'show_ignored_files': 0, 'toggle': 0}]]':"
[denite] Please execute :messages command.
```

**Comment by Shougo** [comment]
This is invalid.

Because,

```
function! s:defx_settings()
    function! s:denite_dir_rec(context) abort
        let narrow_dir = a:context.targets[0]
        execute 'Denite -default-action=defx ' .
                    \ 'directory_rec:' . narrow_dir
    endfunction
    nnoremap <silent><buffer><expr> <A-c>
                \ defx#do_action('call', '<SID>denite_dir_rec')
endfunction
```

You must not use `<SID>` function for it.

It must be:

```vim
function! s:denite_dir_rec(context) abort
      let narrow_dir = a:context.targets[0]
      execute 'Denite -default-action=defx ' .
                  \ 'directory_rec:' . narrow_dir
endfunction
function! s:Test(context) abort
  echomsg string(a:context.targets)
endfunction
function! s:SID_PREFIX() abort
  return matchstr(expand('<sfile>'),
  \ '<SNR>\d\+_\zeSID_PREFIX$')
endfunction
let g:sid = s:SID_PREFIX()
function! s:defx_settings()
    nnoremap <silent><buffer><expr> <A-c>
                \ defx#do_action('call', g:'denite_dir_rec')
endfunction
```

Why don't read the documentation?

```
call 						*defx-action-call*
		Call the function.
		You can get the files path as "a:context.targets".

		Action args:
			0. function name
			Note: It must be string.  You cannot use |funcref| or
			|lambda|.

		Example: >

		function! Test(context) abort
		  echomsg string(a:context.targets)
		endfunction
		nnoremap <silent><buffer><expr> f
		\ defx#do_action('call', 'Test')

		" or you can use SID hack
		function! s:Test(context) abort
		  echomsg string(a:context.targets)
		endfunction
		function! s:SID_PREFIX() abort
		  return matchstr(expand('<sfile>'),
		  \ '<SNR>\d\+_\zeSID_PREFIX$')
		endfunction
		let g:sid = s:SID_PREFIX()
  		nnoremap <silent><buffer><expr> f
  		\ defx#do_action('call', g:sid.'Test')
```

Please read the documentation carefully.

Note:  I have used 1.5 hours to detect the reason.

**Comment by petobens** [comment]
Sorry for your trouble.
