### ISSUE TITLE
Defx stops working with rpcrequest error

### ISSUE THREAD

**Issue by ljohnston** [Shougo/defx.nvim#173]
# Problems summary
After starting MacVim and using defx/denite for a while, an attempt to open one or the other will eventually fail with something similar to the following error message:
```
Error detected while processing function defx#util#call_defx[2]..defx#start[5]..defx#util#rpcrequest[12]..yarp#core#request[2].
.neovim_rpc#rpcrequest:
line   14:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: '274'
E858: Eval did not return a valid python object
E714: List required
line   15:
E121: Undefined variable: err
line   21:
E121: Undefined variable: result
```
After getting the above error, any attempt to bring up either defx or denite will result in a similar error message:
```
Error detected while processing function defx#util#call_defx[2]..defx#start[5]..defx#util#rpcrequest[12]..yarp#core#request[2].
.neovim_rpc#rpcrequest:
line    9:
E906: not an open channel
line   14:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: '275'
E858: Eval did not return a valid python object
E714: List required
line   15:
E121: Undefined variable: err
line   21:
E121: Undefined variable: result
```
The only way that I've been able to get things working again is to restart MacVim.
## Expected
I'd expect defx/denite to keep working for the duration of the MacVim session.

## Environment Information

 * defx version(SHA1):  b07750005ba3fd72d9452f7d33a1c3e74204061a
 * nvim-yarp version(SHA1):  81caad80107abb9c2f5159e02e2cd95876370bec
 * vim-hug-neovim-rpc version(SHA1):  6532acee7a06b2420160279fdd397b9d8e5f1e8a

 * OS: Mac OS Mojave

 * neovim/Vim version:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 29 2019 11:57:42)
macOS version
Included patches: 1-2224
```

 * `:checkhealth` or `:CheckHealth` result(neovim only): N/A

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
Happy to provide this, but I fully realize you're not going to be able to reproduce this problem. What I'm really hoping for here is that you might be able to find something in the log files I've attached that might point toward a problem/solution. If not, so be it.

Note that I've removed any of the denite configuration to keep things under 50 lines.

Also, you'll see some python configuration here. I've tried this with several different python setups (e.g. system python, custom built pythons, etc.)
```vim
let $NVIM_PYTHON_LOG_FILE="/tmp/nvim_log"
let $NVIM_PYTHON_LOG_LEVEL="DEBUG"

set nocompatible

set pyxversion=3
let $PATH = $HOME . '/.vim/python/bin:' . $PATH

if !has('nvim')
    set pythonthreehome=$HOME/.vim/python
    set pythonthreedll=$HOME/.vim/python/lib/libpython3.7m.dylib
endif

call plug#begin('~/.vim/plugged')

    if !has('nvim')
        Plug 'roxma/nvim-yarp'
        Plug 'roxma/vim-hug-neovim-rpc'
    endif

    Plug 'Shougo/denite.nvim', { 'tag': '3.0' }
    Plug 'Shougo/defx.nvim', { 'tag': '1.0' }

call plug#end()

let mapleader = "\<Space>"
let g:mapleader = "\<Space>"

nnoremap <leader>e :Defx<cr>

autocmd FileType defx call s:DefxSettings()

function! s:DefxSettings() 
    nnoremap <silent><buffer><expr> <CR> defx#do_action('open')
    nnoremap <silent><buffer><expr> -    defx#do_action('cd', ['..'])
    nnoremap <silent><buffer><expr> q    defx#do_action('quit')
endfunction
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Start MacVim
 2. Periodically use defx/denite for  some period of time, could be a few hours or a few days.
 3. An attempt to bring up one or the other will eventually produce the error output shown in the summary.

## Generate a logfile if appropriate

Log files attached:
[nvim_log_py3_defx.gz](https://github.com/Shougo/defx.nvim/files/3827567/nvim_log_py3_defx.gz)
[nvim_log_py3_denite.gz](https://github.com/Shougo/defx.nvim/files/3827568/nvim_log_py3_denite.gz)
[nvim_log_py3_neovim_rpc_server.gz](https://github.com/Shougo/defx.nvim/files/3827569/nvim_log_py3_neovim_rpc_server.gz)

**Comment by Shougo** [comment]
It is not defx/denite problem.
The child process seems crashed.

**Comment by Shougo** [comment]
I have read the log.

```
2019-11-06 14:19:57,220 [DEBUG @ msgpack_stream.py:_on_data:58] 19203 - waiting for message...
2019-11-06 14:19:57,220 [DEBUG @ msgpack_stream.py:_on_data:63] 19203 - unpacker needs more data...
2019-11-06 14:19:57,220 [DEBUG @ msgpack_stream.py:_on_data:58] 19203 - waiting for message...
2019-11-06 14:19:57,220 [DEBUG @ msgpack_stream.py:_on_data:60] 19203 - received message: [1, 5700, None, None]
2019-11-06 14:19:57,220 [DEBUG @ async_session.py:_on_response:100] 19203 - received response: None, None
2019-11-06 14:19:57,221 [DEBUG @ session.py:response_cb:159] 19203 - response is available for greenlet <greenlet.greenlet object at 0x10ac6f940>, switching back
2019-11-06 14:19:57,221 [DEBUG @ session.py:handler:197] 19203 - greenlet <greenlet.greenlet object at 0x10ac6f940> finished executing, sending None as response
2019-11-06 14:19:57,221 [DEBUG @ async_session.py:send:138] 19203 - sending response to request 247: [1, 247, None, None]
2019-11-06 14:19:57,221 [DEBUG @ msgpack_stream.py:send:33] 19203 - sent [1, 247, None, None]
2019-11-06 14:19:57,221 [DEBUG @ base.py:send:117] 19203 - Sending 'b'\x94\x01\xcc\xf7\xc0\xc0''
2019-11-06 14:19:57,221 [DEBUG @ session.py:handler:207] 19203 - greenlet <greenlet.greenlet object at 0x10ac6f940> is now dying...
2019-11-06 14:19:57,221 [DEBUG @ msgpack_stream.py:_on_data:58] 19203 - waiting for message...
2019-11-06 14:19:57,221 [DEBUG @ msgpack_stream.py:_on_data:63] 19203 - unpacker needs more data...
2019-11-07 13:18:34,916 [DEBUG @ base.py:_on_signal:162] 19203 - Received SIGTERM
2019-11-07 13:18:34,918 [DEBUG @ base.py:stop:153] 19203 - Stopped event loop
2019-11-07 13:18:34,918 [DEBUG @ base.py:run:144] 19203 - Exited event loop
2019-11-07 13:18:34,920 [DEBUG @ base.py:close:158] 19203 - Closed event loop
```

**Comment by Shougo** [comment]
I don't know why it dying.

**Comment by Shougo** [comment]
Please test neovim instead.

**Comment by Shougo** [comment]
No response?

**Comment by ljohnston** [comment]
As this is a seemingly randomly occurring problem, I wanted to use neovim long enough to make sure that the issue wasn't going to resurface. It's been a week now and I've not seen it happen. I'm confident in saying that this is not a problem when using neovim.

**Comment by Shougo** [comment]
Hm...   OK.  I cannot fix the crash problem from the information.
