### ISSUE TITLE
Why I `:Defx C:\Users\10786`(it is my `$HOME`) will get this error? Thanks!

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/defx.nvim#182]
```
|| [defx@yarp] error caught in request handler '_defx_start [[['C:\\Users\\10786\\'], {'columns': 'indent:mark:git:icons:filename:type:size:time', 'auto_cd': 0, 'prev_bufnr': 1, 'root_marker': '[in]: ', 'resume': 1, 'auto_recursive_level': 0, 'sort': 'filename', 'listed': 0, 'new': 0, 'ignored_files': '.*', 'direction': 'topleft', 'visual_end': 0, 'winheight': 30, 'profile': 0, 'search': '', 'buffer_name': '', 'winwidth': 28, 'split': 'vertical', 'visual_start': 0, 'cursor': 16, 'winrelative': 'editor', 'prev_winid': 1000, 'wincol': 43, 'winrow': 14, 'session_file': '', 'show_ignored_files': 0, 'drives': [], 'toggle': 0}]]'<0d>
|| [defx@yarp] Traceback (most recent call last):<0d>
|| [defx@yarp]   File "C:\Users\10786\vimfiles\repos\github.com\roxma\nvim-yarp\pythonx\yarp.py", line 29, in on_request<0d>
|| [defx@yarp]     return getattr(module_obj, method)(*args)<0d>
|| [defx@yarp]   File "C:\Users\10786\vimfiles\repos\github.com\Shougo\defx.nvim\rplugin\python3\defx\__init__.py", line 66, in _defx_start<0d>
|| [defx@yarp]     global_rplugin.start(args)<0d>
|| [defx@yarp]   File "C:\Users\10786\vimfiles\repos\github.com\Shougo\defx.nvim\rplugin\python3\defx\rplugin.py", line 32, in start<0d>
|| [defx@yarp]     views[0].init(paths, context, self._clipboard)<0d>
|| [defx@yarp]   File "C:\Users\10786\vimfiles\repos\github.com\Shougo\defx.nvim\rplugin\python3\defx\view.py", line 51, in init<0d>
|| [defx@yarp]     if not self._init_defx(paths, clipboard):<0d>
|| [defx@yarp]   File "C:\Users\10786\vimfiles\repos\github.com\Shougo\defx.nvim\rplugin\python3\defx\view.py", line 392, in _init_defx<0d>
|| [defx@yarp]     self.redraw(True)<0d>
|| [defx@yarp]   File "C:\Users\10786\vimfiles\repos\github.com\Shougo\defx.nvim\rplugin\python3\defx\view.py", line 145, in redraw<0d>
|| [defx@yarp]     for x in self._candidates<0d>
|| [defx@yarp]   File "C:\Users\10786\vimfiles\repos\github.com\Shougo\defx.nvim\rplugin\python3\defx\view.py", line 145, in <listcomp><0d>
|| [defx@yarp]     for x in self._candidates<0d>
|| [defx@yarp]   File "C:\Users\10786\vimfiles\repos\github.com\Shougo\defx.nvim\rplugin\python3\defx\view.py", line 604, in _get_columns_text<0d>
|| [defx@yarp]     text = column.get(context, candidate)<0d>
|| [defx@yarp]   File "C:\Users\10786\vimfiles\repos\github.com\Shougo\defx.nvim\rplugin\python3\defx\column\size.py", line 26, in get<0d>
|| [defx@yarp]     size = self._get_size(path.stat().st_size)<0d>
|| [defx@yarp]   File "D:\Program Files\Python\Python37\lib\pathlib.py", line 1151, in stat<0d>
|| [defx@yarp]     return self._accessor.stat(self)<0d>
|| [defx@yarp] FileNotFoundError: [WinError 2] ϵͳ<d5>Ҳ<bb><b5><bd>ָ<b6><a8><b5><c4><ce>ļ<fe><a1><a3>: 'C:\\Users\\10786\\My Documents'<0d>
|| [defx@yarp] <0d>
```

OS: windows10
vim: gvim8.1
python: 3.7

**Comment by Shougo** [comment]
Backslash is considered as escape sequence.

**Comment by Shougo** [comment]
I have added error check.
