### ISSUE TITLE
Renaming a directory causes pynvim.api.common.NvimError: Vim(saveas):E502: "[directory]" is a directory

### ISSUE THREAD

**Issue by purefun** [Shougo/defx.nvim#282]
# Problems summary

Renaming a directory causes `pynvim.api.common.NvimError: Vim(saveas):E502: "[directory]" is a directory`

## Expected

Rename successfully.

## Environment Information

 * plugin version(SHA1): d523067907465a7845dddd80a7e524926a401344 

 * OS: macOS Version 10.15.6

 * neovim/Vim version:
```
:version
NVIM v0.5.0-dev+7afd4526f
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthr
ough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20201224
-59988-zvrge9/build/config -I/tmp/neovim-20201224-59988-zvrge9/src -I/usr/local/include -I/tmp/neovim-20201224-59988-zvrge9/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
 -I/usr/local/opt/gettext/include -I/tmp/neovim-20201224-59988-zvrge9/build/src/nvim/auto -I/tmp/neovim-20201224-59988-zvrge9/build/include
Compiled by Nil@Nil-mbp.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-7afd452/share/nvim"

Run :checkhealth for more info
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
:version
NVIM v0.5.0-dev+7afd4526f
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthr
ough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20201224
-59988-zvrge9/build/config -I/tmp/neovim-20201224-59988-zvrge9/src -I/usr/local/include -I/tmp/neovim-20201224-59988-zvrge9/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
 -I/usr/local/opt/gettext/include -I/tmp/neovim-20201224-59988-zvrge9/build/src/nvim/auto -I/tmp/neovim-20201224-59988-zvrge9/build/include
Compiled by Nil@Nil-mbp.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-7afd452/share/nvim"

Run :checkhealth for more info

```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=/Users/Nil/Playground/defx-rename-issue/defx.nvim

nnoremap <silent>_ :Defx -show-ignored-files<CR>
nnoremap <silent>- :Defx `expand('%:p:h')` -search=`expand('%:p')` -show-ignored-files<CR>

autocmd FileType defx call s:defx_my_settings()

function! s:defx_my_settings() abort
  setlocal cursorline
  nnoremap <silent><buffer><expr> <CR>     defx#do_action('open')
  nnoremap <silent><buffer><expr> c        defx#do_action('copy')
  nnoremap <silent><buffer><expr> M        defx#do_action('move')
  nnoremap <silent><buffer><expr> p        defx#do_action('paste')
  nnoremap <silent><buffer><expr> l        defx#do_action('open')
  nnoremap <silent><buffer><expr> E        defx#do_action('open', 'vsplit')
  nnoremap <silent><buffer><expr> P        defx#do_action('open', 'pedit')
  nnoremap <silent><buffer><expr> o        defx#do_action('open_or_close_tree')
  nnoremap <silent><buffer><expr> K        defx#do_action('new_directory')
  nnoremap <silent><buffer><expr> N        defx#do_action('new_file')
  " nnoremap <silent><buffer><expr> M        defx#do_action('new_multiple_files')
  nnoremap <silent><buffer><expr> C        defx#do_action('toggle_columns', 'mark:indent:icon:filename:type:size:time:git')
  nnoremap <silent><buffer><expr> S        defx#do_action('toggle_sort', 'time')
  nnoremap <silent><buffer><expr> dd       defx#do_action('remove', 'false')
  nnoremap <silent><buffer><expr> r        defx#do_action('rename')
  nnoremap <silent><buffer><expr> !        defx#do_action('execute_command')
  nnoremap <silent><buffer><expr> x        defx#do_action('execute_system')
  nnoremap <silent><buffer><expr> yy       defx#do_action('yank_path')
  nnoremap <silent><buffer><expr> .        defx#do_action('toggle_ignored_files')
  nnoremap <silent><buffer><expr> h        defx#do_action('cd', ['..'])
  nnoremap <silent><buffer><expr> -        defx#do_action('cd', ['..'])
  nnoremap <silent><buffer><expr> _        defx#do_action('open_directory', getcwd())
  nnoremap <silent><buffer><expr> q        defx#do_action('quit')
  nnoremap <silent><buffer><expr> m        defx#do_action('toggle_select') . 'j'
  nnoremap <silent><buffer><expr> t        defx#do_action('toggle_select_all')
  nnoremap <silent><buffer><expr> *        defx#do_action('clear_select_all')
  nnoremap <silent><buffer><expr> j        line('.') == line('$') ? 'gg' : 'j'
  nnoremap <silent><buffer><expr> k        line('.') == 1 ? 'G' : 'k'
  nnoremap <silent><buffer><expr> <C-l>    defx#do_action('redraw')
  nnoremap <silent><buffer><expr> <C-g>    defx#do_action('print')
  nnoremap <silent><buffer><expr> cd       defx#do_action('change_vim_cwd')
endfunction
```

## The reproduce ways from neovim/Vim starting (Required!)

1. git clone https://github.com/Shougo/defx.nvim.git
2. create and fill init.vim file
3. open vim `NVIM_PYTHON_LOG_FILE=$HOME/desktop/log NVIM_PYTHON_LOG_LEVEL=DEBUG XDG_CONFIG_HOME=$HOME/Playground/defx-rename-issue vim`
3. create a directory (name: demo), with a file (name: a.txt) within it
4. open the file a.txt, **and keep it open**
5. split the window, open defx, navigate to the `demo` directory
6. rename `demo` to `demo1`

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screen shot (if possible)

https://user-images.githubusercontent.com/3140656/103192863-4246a900-4915-11eb-9b53-041c533d9ed3.mp4

```
Error detected while processing function defx#call_action[9]..defx#util#rpcrequest:
line   18:
Error invoking '_defx_do_action' on channel 4 (python3-rplugin-host):
error caught in request handler '_defx_do_action [['rename', [], {'columns': 'mark:indent:icon:filename:type', 'winrelative': 'editor', 'auto_cd': False, 'prev_bufnr': 1, 'root_marker': '[in] ', 'resume': False, '
close': False, 'auto_recursive_level': 0, 'sort': 'filename', 'listed': False, 'new': False, 'ignored_files': '.*', 'focus': True, 'direction': '', 'visual_end': 0, 'winheight': 30, 'profile': False, 'preview_heig
ht': 12, 'buffer_name': 'default', 'winwidth': 90, 'filtered_files': '', 'split': 'no', 'preview_width': 40, 'visual_start': 0, 'cursor': 4, 'prev_last_bufnr': 1, 'search': '', 'prev_winid': 1001, 'wincol': 53, 'w
inrow': 19, 'session_file': '', 'floating_preview': False, 'vertical_preview': False, 'show_ignored_files': False, 'drives': [], 'toggle': False}]]':
Traceback (most recent call last):
  File "/Users/Nil/.vim/plugged/defx.nvim/rplugin/python3/defx/__init__.py", line 39, in do_action
    self._rplugin.do_action(args)
  File "/Users/Nil/.vim/plugged/defx.nvim/rplugin/python3/defx/rplugin.py", line 39, in do_action
    view.do_action(args[0], args[1], args[2])
  File "/Users/Nil/.vim/plugged/defx.nvim/rplugin/python3/defx/view.py", line 130, in do_action
    ret = action.do_action(self, defx, action_name, context)
  File "/Users/Nil/.vim/plugged/defx.nvim/rplugin/python3/defx/action.py", line 62, in do_action
    action.func(view, defx, context)
  File "/Users/Nil/.vim/plugged/defx.nvim/rplugin/python3/defx/kind/file.py", line 662, in _rename
    view._vim.call('defx#util#buffer_rename',
  File "/usr/local/lib/python3.9/site-packages/pynvim/api/nvim.py", line 299, in call
    return self.request('nvim_call_function', name, args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim(saveas):E502: "~/Playground/defx-rename-issue/demo1" is a directory

```

## Upload the log file
it's empty.

**Comment by Shougo** [comment]
Please wait.  I will check.

**Comment by Shougo** [comment]
reproduced.

**Comment by Shougo** [comment]
Fixed.

**Comment by purefun** [comment]
Wow, thank you for super fast fix.
