### ISSUE TITLE
Some errors when send some file to trash using neovim in Macos(Big Sur)

### ISSUE THREAD

**Issue by thehappyboy** [Shougo/defx.nvim#283]
I also search this in google and find some message(https://stackoverflow.com/questions/14699604/replacements-for-getmacosstatuserrorstring-getmacosstatuscommentstring). it looks like the "GetMacOSStatusCommentString" function not work in Macos now. I don't know how to fix that.

Are you sure you want to delete /Users/john/.config/nvim/rc/jb.py?

处理 function defx#call_action[9]..defx#util#rpcrequest 时发生错误:
第   18 行:
Error invoking '_defx_do_action' on channel 5 (python3-rplugin-host):
error caught in request handler '_defx_do_action [['remove_trash', [], {'columns': 'mark:indent:git:icons:filename', 'winrelative': 'editor', '
auto_cd': False, 'prev_bufnr': 2, 'root_marker': '[in]: ', 'resume': 1, 'close': False, 'auto_recursive_level': 0, 'sort': 'filename', 'listed'
: False, 'new': False, 'ignored_files': '.*', 'focus': True, 'direction': 'topleft', 'visual_end': 0, 'winheight': 30, 'profile': False, 'previ
ew_height': 12, 'buffer_name': 'default', 'winwidth': 30, 'filtered_files': '', 'split': 'vertical', 'preview_width': 40, 'visual_start': 0, 'c
ursor': 15, 'prev_last_bufnr': -1, 'search': '', 'prev_winid': 1005, 'wincol': 35, 'winrow': 14, 'session_file': '', 'floating_preview': False,
 'vertical_preview': False, 'show_ignored_files': 0, 'drives': [], 'toggle': False}]]':
Traceback (most recent call last):
  File "/Users/john/.cache/dein/repos/github.com/Shougo/defx.nvim/rplugin/python3/defx/__init__.py", line 39, in do_action
    self._rplugin.do_action(args)
  File "/Users/john/.cache/dein/repos/github.com/Shougo/defx.nvim/rplugin/python3/defx/rplugin.py", line 39, in do_action
    view.do_action(args[0], args[1], args[2])
  File "/Users/john/.cache/dein/repos/github.com/Shougo/defx.nvim/rplugin/python3/defx/view.py", line 130, in do_action
    ret = action.do_action(self, defx, action_name, context)
  File "/Users/john/.cache/dein/repos/github.com/Shougo/defx.nvim/rplugin/python3/defx/action.py", line 62, in do_action
    action.func(view, defx, context)
  File "/Users/john/.cache/dein/repos/github.com/Shougo/defx.nvim/rplugin/python3/defx/kind/file.py", line 621, in _remove_trash
    import send2trash
  File "/Users/john/miniconda3/envs/neovim/lib/python3.9/site-packages/send2trash/__init__.py", line 12, in <module>
    from .plat_osx import send2trash
  File "/Users/john/miniconda3/envs/neovim/lib/python3.9/site-packages/send2trash/plat_osx.py", line 17, in <module>
    GetMacOSStatusCommentString = Foundation.GetMacOSStatusCommentString
  File "/Users/john/miniconda3/envs/neovim/lib/python3.9/ctypes/__init__.py", line 395, in __getattr__
    func = self.__getitem__(name)
  File "/Users/john/miniconda3/envs/neovim/lib/python3.9/ctypes/__init__.py", line 400, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, GetMacOSStatusCommentString): symbol not found

**Comment by Shougo** [comment]
It is send2trash problem.  Please read it.
https://github.com/arsenetar/send2trash/issues/24

**Comment by Shougo** [comment]
I don't like macOS backward compatibility.  Huh.

**Comment by Shougo** [comment]
You can send fix PR to send2trash.

**Comment by thecontinium** [comment]
This problem was resolves using python 3.9.2.
