### ISSUE TITLE
Defx requires netrw to be loaded

### ISSUE THREAD

**Issue by Fnatte** [Shougo/defx.nvim#293]
# Problems summary

I get an error `pynvim.api.common.NvimError: Vim:E93: More than one match for` (see full stack trace below) when using defx without netrw.

## Expected

1. defx works without netrw
2. or, add notice in `:help` that netrw is required 

## Environment Information

 * plugin version(SHA1): 6224e6981dc33887bc045a7eab7df6f94106c4af
 * OS: Linux
 * neovim/Vim version: v0.4.4

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
function! DoRemote(arg)
	UpdateRemotePlugins
endfunction

call plug#begin()

Plug 'Shougo/defx.nvim', { 'do': ':UpdateRemotePlugins' }
nnoremap <C-n> :Defx -listed -resume<CR>

call plug#end()

" Disable netrw
let g:loaded_netrwPlugin       = 1

autocmd FileType defx call s:defx_my_settings()
function! s:defx_my_settings() abort
        " Define mappings
        nnoremap <silent><buffer><expr> l defx#is_directory() ?
                \ defx#do_action('open_tree') : defx#do_action('open')
endfunction
```

Note that I can get it to work by just using this additional config:
```
augroup FileExplorer
 au!
 au VimEnter *	sil call s:VimEnter(expand("<amatch>"))
augroup END

fun! s:VimEnter(dirname)
  if isdirectory(a:dirname)
   sil! call netrw#LocalBrowseCheck(a:dirname)
  endif
endfun
```

It seems like defx need that `netrw#LocalBrowseCheck` is called?

## The reproduce ways from neovim/Vim starting (Required!)

 1. `nvim -u init.vim .`
 2. `ctrl-n`
 3. Open a file

## Error

```
2021-03-20 14:29:22,626 [WARNING @ session.py:handler:200] 311238 - error response from request '_defx_do_action [['open', [], {'columns': 'mark:indent:icon:filename:type', 'winrelative': 'editor', 'auto_cd': False, 'prev_bufnr': 2, 'root_marker': '[in] ', 'resume': False, 'close': False, 'auto_recursive_level': 0, 'sort': 'filename', 'listed': False, 'new': False, 'ignored_files': '.*', 'focus': True, 'direction': '', 'visual_end': 0, 'winheight': 30, 'profile': False, 'preview_height': 12, 'buffer_name': 'default', 'winwidth': 90, 'filtered_files': '', 'split': 'no', 'preview_width': 40, 'visual_start': 0, 'cursor': 4, 'prev_last_bufnr': -1, 'search': '', 'prev_winid': 1000, 'wincol': 47, 'winrow': 16, 'session_file': '', 'floating_preview': False, 'vertical_preview': False, 'show_ignored_files': False, 'drives': [], 'toggle': False}]]': Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynvim/plugin/host.py", line 102, in _wrap_function
    return fn(*args)
  File "/home/.../.config/nvim/plugged/defx.nvim/rplugin/python3/defx/__init__.py", line 40, in do_action
    self._rplugin.do_action(args)
  File "/home/.../.config/nvim/plugged/defx.nvim/rplugin/python3/defx/rplugin.py", line 41, in do_action
    view.do_action(args[0], args[1], args[2])
  File "/home/.../.config/nvim/plugged/defx.nvim/rplugin/python3/defx/view.py", line 131, in do_action
    ret = action.do_action(self, defx, action_name, context)
  File "/home/.../.config/nvim/plugged/defx.nvim/rplugin/python3/defx/action.py", line 62, in do_action
    action.func(view, defx, context)
  File "/home/.../.config/nvim/plugged/defx.nvim/rplugin/python3/defx/kind/file.py", line 462, in _open
    view.restore_previous_buffer(view._prev_bufnr)
  File "/home/.../.config/nvim/plugged/defx.nvim/rplugin/python3/defx/view.py", line 425, in restore_previous_buffer
    self._vim.call('setreg', '#',
  File "/usr/lib/python3.9/site-packages/pynvim/api/nvim.py", line 299, in call
    return self.request('nvim_call_function', name, args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim:E93: More than one match for /home/.../Code/tmp/

```

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
Fixed.

**Comment by Fnatte** [comment]
> Fixed.

Works great. Thanks!
