### ISSUE TITLE
Errors when using do_action with custom vim function

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#43]
With `vimfiler` I can use the following to open ranger file manager at the current directory:
```vim
        if executable('ranger')
            nmap <buffer>ge <Plug>(vimfiler_cd_vim_current_dir)
                        \ <C-u>:call <SID>TmuxSplitCmd('ranger')<CR>
        endif
```
where the `TmuxSplitCmd` function is:
```vim
function! s:TmuxSplitCmd(cmd)
    if empty('$TMUX')
        return
    endif
   silent execute '!tmux split-window -p 30 -c '. getcwd() . ' ' . a:cmd
endfunction
```

I'm trying to do the same with defx:
```vim
    if s:is_linux && executable('ranger')
        nmap <silent><buffer><expr>ge defx#do_action('change_vim_cwd',
                    \ "call <SID>TmuxSplitCmd('ranger')")
    endif
```
but I get the following error
```

Error detected while processing function defx#_do_action[6]..defx#util#rpcrequest[15].._defx_do_action[1]..remote#define#request:
line    2:
error caught in request handler '/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx:function:_defx_do_action [['change_vim_cwd', ["call <SNR>1_TmuxSplitCmd('ranger')"], {
'columns': 'mark:filename:type', 'auto_cd': False, 'prev_bufnr': 7, 'resume': False, 'listed': False, 'new': False, 'fnamewidth': 100, 'direction': '', 'winheight': 0, 'profile': False, 'search': '', 'buffer_name
': 'default', 'winwidth': 0, 'split': 'no', 'cursor': 22, 'toggle': False}]]':
Traceback (most recent call last):
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/__init__.py", line 41, in do_action
    self._rplugin.do_action(args)
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/rplugin.py", line 37, in do_action
    view.do_action(args[0], args[1], args[2])
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/view.py", line 321, in do_action
    ret = action.do_action(self, defx, action_name, context)
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/action.py", line 38, in do_action
    action.func(view, defx, context)
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/action.py", line 74, in _change_vim_cwd
    view._vim.command(f'silent {command} {defx._cwd}')
  File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b'Vim(call):E488: Trailing characters'
Error detected while processing function defx#_do_action[6]..defx#util#rpcrequest:
line   15:
E171: Missing :endif
```

**Comment by Shougo** [comment]
`change_vim_cwd` argument must be `command` instead of `function`.

You must define the wrapper function.

**Comment by petobens** [comment]
Unfortunately I don't understand what you mean by this (and cannot find examples of how to do it). Can you please explain it? Thanks!

**Comment by Shougo** [comment]
```
function! s:TmuxSplitCmd(cmd, cwd)
    if empty('$TMUX')
        return
    endif
   silent execute '!tmux split-window -p 30 -c '. a:cwd . ' ' . a:cmd
endfunction
command! -nargs=1 TmuxSplit call s:TmuxSplitCommand('ranger', <q-args>)
nmap <silent><buffer><expr>ge defx#do_action('change_vim_cwd',
                    \ "TmuxSplit")
```

Why don't you consider the code?
I am very busy to develop plugins.

**Comment by petobens** [comment]
Thanks!

**Comment by petobens** [comment]
Hi @Shougo. This seems broken now. With the following minimal vimrc:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim
filetype plugin indent on

call defx#custom#option('_', {
            \ 'winwidth': 40,
            \ 'split': 'vertical',
            \ 'direction': 'topleft',
            \ })

augroup ps_defx
    au!
    au FileType defx call s:defx_settings()
augroup END

function! s:TmuxSplitCmd(cmd, cwd)
    if empty('$TMUX')
        return
    endif
    if a:cwd ==# ''
        let cwd = getcwd()
    else
        let cwd = a:cwd
    endif
   silent execute '!tmux split-window -p 30 -c '. cwd . ' ' . a:cmd
endfunction

function! s:defx_settings()
    nnoremap <silent><buffer><expr> q defx#do_action('quit')
    if executable('ranger')
        command! -nargs=1 TmuxRanger call s:TmuxSplitCmd('ranger', <q-args>)
        nmap <silent><buffer><expr>ge defx#do_action('change_vim_cwd',
                    \ "TmuxRanger")
    endif
endfunction
```
If I open `:Defx` and press `ge` then nothing happens. Any pointers? Thanks in advance

**Comment by Shougo** [comment]
@petobens I have removed `change_vim_cwd`'s argument to fix `#104` problem.
Please use `call` action instead.

**Comment by petobens** [comment]
I'm afraid I don't follow. None of the following works:
```viml
call defx#do_action('call', ['TmuxRanger'])
call defx#call_action('TmuxRanger')
call defx#call_action('do_action', 'TmuxRanger')
```

**Comment by Shougo** [comment]
Why don't read the documentation?

```
call 						*defx-action-call*
		Call the function.
		You can get the files path as "a:context.targets".

		Action args:
			0. function name
			Note: It must be string.  You cannot use |funcref| or
			|lambda|.

		Example: >

		function! Test(context) abort
		  echomsg string(a:context.targets)
		endfunction
		nnoremap <silent><buffer><expr> f
		\ defx#do_action('call', 'Test')

		" or you can use SID hack
		function! s:Test(context) abort
		  echomsg string(a:context.targets)
		endfunction
		function! s:SID_PREFIX() abort
		  return matchstr(expand('<sfile>'),
		  \ '<SNR>\d\+_\zeSID_PREFIX$')
		endfunction
		let g:sid = s:SID_PREFIX()
  		nnoremap <silent><buffer><expr> f
  		\ defx#do_action('call', g:sid.'Test')
```

`call` action argument must be `function` instead of `command`.
