### ISSUE TITLE
Feature request: Close Defx buffer after opening a file

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#67]
As per https://github.com/Shougo/defx.nvim/issues/66#issuecomment-451749555

**Comment by Shougo** [comment]
The multiple actions support is needed to implement the feature.

vimfiler has `-auto-quit` feature, but I don't want to another option for it.

**Comment by petobens** [comment]
>  vimfiler has -auto-quit feature, but I don't want to another option for it.

Why not? It's a natural option to have since it addresses a standard use case: open the file explorer to select a file, actually select a candidate and have the file explorer close after that.
Besides for instance denite has `-post-action` that allows to `quit` the denite buffer also.

**Comment by Shougo** [comment]
@petobens Because, the option depends on action implementation.

For example, in vimfiler some option works for `-auto-quit` but some option does not work.
The behavior should be customized by user.

**Comment by Shougo** [comment]
Yes.

**Comment by Shougo** [comment]
For example:

```vim
nnoremap <silent><buffer><expr> <CR> defx#do_action(['drop', 'quit'])
```

**Comment by Shougo** [comment]
```vim
nnoremap <silent><buffer><expr> <CR> defx#do_action('multi', ['drop', 'quit'])
```

**Comment by petobens** [comment]
Thanks for making the change. I have a couple of questions:
i) Using `nnoremap <silent><buffer><expr> <CR> defx#do_action('multi', ['drop', 'quit'])` on a directory simply makes defx close. So how do I change the mapping so that `<CR>` behaves as `defx#do_action('multi', ['drop', 'quit'])` on files but just as `drop` when there is a directory (i.e when there is a directory under the cursor I want to get into it)
i) How do I use 'multi` with vertical and horizontal split actions? I want to open in a horizontal split and close the defx buffer but the following doesn't quite work
```
nnoremap <silent><buffer><expr> s defx#do_action('multi', ['drop', 'split', 'quit'])
```

**Comment by Shougo** [comment]
> i) How do I use 'multi` with vertical and horizontal split actions? I want to open in a horizontal split and close the defx buffer but the following doesn't quite work

I have added the documentation.

> when there is a directory (i.e when there is a directory under the cursor I want to get into it)

I have added `defx#is_directory()`.

**Comment by petobens** [comment]
Thank you for this changes! I've detected one minor issue though. Consider the following minimal vimrc 
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim
filetype plugin indent on

call defx#custom#option('_', {
            \ 'winwidth': 40,
            \ 'split': 'vertical',
            \ 'direction': 'topleft',
            \ })
call defx#custom#column('filename', {'min_width': 23, 'max_width': 23})

augroup ps_defx
    au!
    au FileType defx call s:defx_settings()
augroup END

function! s:defx_settings()
    nnoremap <silent><buffer><expr> <CR>
        \ defx#is_directory() ? defx#do_action('open') :
        \ defx#do_action('multi', ['drop', 'quit'])
    nnoremap <silent><buffer><expr> s
        \ defx#do_action('multi', [['drop', 'split'], 'quit'])
    nnoremap <silent><buffer><expr> v
        \ defx#do_action('multi', [['drop', 'vsplit'], 'quit'])
endfunction
```
Now do the following
i) Open nvim
ii) Run `:Defx` and open one candidate file with `<CR>`.
ii) Run `:Defx` again and press either `v` or `s` on a candidate -> this triggers the following error:
```
Error detected while processing function defx#call_action[7]..defx#util#rpcrequest:
line   18:
error caught in request handler '_defx_do_action [['multi', [['drop', 'vsplit'], 'quit'], {'columns': 'mark:filename:type', 'auto_cd': False, 'prev_bufnr': 3, 'resume': False, 'sort': 'filename', 'listed': False,
'new': False, 'direction': 'topleft', 'show_ignored_files': False, 'winheight': 0, 'profile': False, 'search': '', 'buffer_name': 'default', 'winwidth': 40, 'split': 'vertical', 'cursor': 13, 'prev_winid': 1002, '
toggle': False}]]':
Traceback (most recent call last):
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/__init__.py", line 41, in do_action
    self._rplugin.do_action(args)
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/rplugin.py", line 37, in do_action
    view.do_action(args[0], args[1], args[2])
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/view.py", line 398, in do_action
    ret = action.do_action(self, defx, action_name, context)
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/action.py", line 43, in do_action
    action.func(view, defx, context)
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/base/kind.py", line 67, in _multi
    do_action(view, defx, args[0], context._replace(args=args[1:]))
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/action.py", line 43, in do_action
    action.func(view, defx, context)
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/base/kind.py", line 76, in _quit
    view.quit()
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/view.py", line 230, in quit
    self._vim.command('close')
  File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/pedro/.local/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b'Vim(let):error caught while executing async callback:'
```

After the error the new file eventually does open in a split but the cursor position doesn't go to the newly opened file and remains in the old one (I believe it should move to the new file).

**Comment by Shougo** [comment]
I have tested it and I don't reproduce your error.

My tested vimrc is:

```
set runtimepath+=~/work/defx.nvim/

filetype plugin indent on
syntax enable

call defx#custom#option('_', {
      \ 'winwidth': 40,
      \ 'split': 'vertical',
      \ 'direction': 'topleft',
      \ })
call defx#custom#column('filename', {'min_width': 23, 'max_width': 23})

autocmd FileType defx call s:defx_my_settings()
function! s:defx_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
        \ defx#is_directory() ? defx#do_action('open') :
        \ defx#do_action('multi', ['drop', 'quit'])
  nnoremap <silent><buffer><expr> s
        \ defx#do_action('multi', [['drop', 'split'], 'quit'])
  nnoremap <silent><buffer><expr> v
        \ defx#do_action('multi', [['drop', 'vsplit'], 'quit'])
endfunction
```

Have you tested the minimal vimrc and the reproduce instructions?

**Comment by Shougo** [comment]
Please provide reprouce-able instructions for me.

If other people reproduce the problem, I will investigate though.

**Comment by Shougo** [comment]
The original issue is already resolved.

It should be new issue with more information.

It must be reproduce-able for other people.

**Comment by petobens** [comment]
Ok. I've opened #78 . Thanks
