### ISSUE TITLE
Double filer emulation no longer working

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#76]
Consider the following minimal vimrc
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim
filetype plugin indent on

call defx#custom#option('_', {
            \ 'winwidth': 40,
            \ 'split': 'vertical',
            \ 'direction': 'topleft',
            \ })
call defx#custom#column('filename', {'min_width': 23, 'max_width': 23})

nnoremap <silent> ,xdf :Defx `expand('%:p:h')`<CR>
            \ :Defx -new -split=horizontal -direction=<CR>
            \ :wincmd p<CR>
```
If I now open `nvim` and pres `,xdf` I no longer get a "double filer" feature. In fact when I run ` :Defx -new -split=horizontal -direction=` inside a defx buffer then the following error is triggered:
```
Error detected while processing function defx#util#call_defx[2]..defx#start[8]..defx#util#rpcrequest:
line   18:
error caught in async handler '_defx_async_action [['check_redraw', [], {'columns': 'mark:filename:type', 'auto_cd': False, 'prev_bufnr': 9, 'resume': False, 'sort': 'filename', 'listed': False, 'new': False, 'di
rection': 'topleft', 'show_ignored_files': False, 'winheight': 0, 'profile': False, 'search': '', 'buffer_name': 'default', 'winwidth': 40, 'split': 'vertical', 'cursor': 1, 'prev_winid': 1009, 'toggle': False}]]
'
Traceback (most recent call last):
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/__init__.py", line 45, in async_action
    self._rplugin.do_action(args)
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/rplugin.py", line 37, in do_action
    view.do_action(args[0], args[1], args[2])
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/view.py", line 389, in do_action
    for x in self._defxs}
AttributeError: 'View' object has no attribute '_defxs'
Error detected while processing function defx#util#call_defx[2]..defx#start[8]..defx#util#rpcrequest:
line   18:
error caught in async handler '_defx_async_action [['check_redraw', [], {'columns': 'mark:filename:type', 'auto_cd': False, 'prev_bufnr': 9, 'resume': False, 'sort': 'filename', 'listed': False, 'new': False, 'di
rection': 'topleft', 'show_ignored_files': False, 'winheight': 0, 'profile': False, 'search': '', 'buffer_name': 'default', 'winwidth': 40, 'split': 'vertical', 'cursor': 1, 'prev_winid': 1009, 'toggle': False}]]
'
Traceback (most recent call last):
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/__init__.py", line 45, in async_action
    self._rplugin.do_action(args)
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/rplugin.py", line 37, in do_action
    view.do_action(args[0], args[1], args[2])
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/view.py", line 389, in do_action
    for x in self._defxs}
AttributeError: 'View' object has no attribute '_defxs'
```

**Comment by petobens** [comment]
Thank you! This is working now. I believe I asked this before but: is it possible to do a redraw on the other defx buffer whenever there is a create, rename, delete action on the first defx buffer? Currently we have to manually enter the other defx buffer to trigger an update/redraw of the changes in first defx buffer

**Comment by Shougo** [comment]
I have described before...
The feature is not supported in defx.

**Comment by Shougo** [comment]
> Thank you! This is working now. I believe I asked this before but: is it possible to do a redraw on the other defx buffer whenever there is a create, rename, delete action on the first defx buffer? Currently we have to manually enter the other defx buffer to trigger an update/redraw of the changes in first defx buffer

I have tested it but the behavior is very bad.
You can simulate the behavior by `wincmd w` and enter defx windows automatically.

If you enter defx window, `check_redraw` action fired automatically.

**Comment by Shougo** [comment]
Example:

```vim
function! Defx_all_redraw() abort
  let prev_winnr = winnr()
  for winnr in filter(range(1, winnr('$')), 'v:val !=# winnr()')
    if getbufvar(winbufnr(winnr), '&filetype') ==# 'defx'
      execute winnr . 'wincmd w'
    endif
  endfor
  execute prev_winnr . 'wincmd w'
endfunction
```

**Comment by petobens** [comment]
Thank you!

**Comment by Shougo** [comment]
> Thank you! This is working now. I believe I asked this before but: is it possible to do a redraw on the other defx buffer whenever there is a create, rename, delete action on the first defx buffer? Currently we have to manually enter the other defx buffer to trigger an update/redraw of the changes in first defx buffer

I have implemented the feature.

**Comment by petobens** [comment]
Awesome. Thanks
