### ISSUE TITLE
Crash with double double filer

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#88]
Consider the following minimal vimrc
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim
filetype plugin indent on

call defx#custom#option('_', {
            \ 'winwidth': 40,
            \ 'split': 'vertical',
            \ 'direction': 'topleft',
            \ })

augroup ps_defx
    au!
    au FileType defx call s:defx_settings()
augroup END


function! s:QuitAllDefx(context) abort
    let buffers = filter(range(1, bufnr('$')),
                \ 'getbufvar(v:val, "&filetype") ==# "defx"')
    if !empty(buffers)
        silent execute 'bwipeout' join(buffers)
    endif
endfunction

function! s:defx_settings()
    nnoremap <silent><buffer><expr> Q defx#do_action('call', '<SID>QuitAllDefx')
endfunction

nnoremap <silent> ,df :Defx `expand('%:p:h')`<CR>
            \ :Defx -new -split=horizontal -direction=<CR>
            \ :wincmd p<CR>
```
Now do
1. Open nvim and press `,df` to open defx double filer
2. From within the defx buffer press `Q` to exit (both) defx buffers
3. Press `,df` again

The last step results in the following error:
```
Error detected while processing function defx#util#call_defx[2]..defx#start[8]..defx#util#rpcrequest:
line   18:
error caught in async handler '_defx_async_action [['check_redraw', [], {'columns': 'mark:filename:type', 'auto_cd': False, 'prev_bufnr': 4, 'root_marker': '[in]: ',
'resume': False, 'sort': 'filename', 'listed': False, 'new': False, 'direction': 'topleft', 'show_ignored_files': False, 'winheight': 30, 'profile': False, 'search':
'', 'buffer_name': 'default', 'winwidth': 40, 'split': 'vertical', 'cursor': 2, 'prev_winid': 1004, 'wincol': 41, 'winrow': 16, 'toggle': False}]]'
Traceback (most recent call last):
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/__init__.py", line 45, in async_action
    self._rplugin.do_action(args)
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/rplugin.py", line 37, in do_action
    view.do_action(args[0], args[1], args[2])
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/view.py", line 422, in do_action
    for x in self._defxs}
AttributeError: 'View' object has no attribute '_defxs'
```

**Comment by petobens** [comment]
Thank you!
